version: '3'
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper

  kafka:
    image: trivialis/kafka:1.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    entrypoint:
      - /usr/local/kafka/bin/kafka-server-start.sh
      - /usr/local/kafka/config/server.properties
      - --override
      - zookeeper.connect=zookeeper:2181
      - --override
      - listeners=PLAINTEXT://kafka:$KAFKA_PORT
      - --override
      - advertised.listeners=PLAINTEXT://$KAFKA_HOST:$KAFKA_PORT
    depends_on:
      - zookeeper

  kafka.tls:
    image: trivialis/kafka.tls:1.1.0
    container_name: kafka.tls
    ports:
      - "$KAFKA_PORT:9092"
    entrypoint:
      - /usr/local/kafka/bin/kafka-server-start.sh
      - /usr/local/kafka/config/server.properties
      - --override
      - zookeeper.connect=zookeeper:2181
      - --override
      - security.inter.broker.protocol=SSL
      - --override
      - listeners=SSL://kafka.tls:9092
      - --override
      - advertised.listeners=SSL://$KAFKA_HOST:$KAFKA_PORT
      - --override
      - ssl.keystore.location=/etc/security/tls/server.keystore.jks
      - --override
      - ssl.keystore.password=salzburg
      - --override
      - ssl.key.password=salzburg
      - --override
      - ssl.truststore.location=/etc/security/tls/server.truststore.jks
      - --override
      - ssl.truststore.password=salzburg
      - --override
      - ssl.client.auth=required
    depends_on:
      - zookeeper

  run-test:
    image: maven:3.5.3-alpine
    container_name: maven-build
    volumes:
      - ./..:/opt
      - ~/.m2:/root/.m2
      - ..//tls_certs/client/client.keystore.jks:/etc/security/tls/client.keystore.jks:ro
      - ../tls_certs/client/client.truststore.jks:/etc/security/tls/client.truststore.jks:ro
    entrypoint:
      -  mvn
      - -f
      - /opt/pom.xml
      - -Dkafka.topic=log4j2-kafka-topic
      - -DstorePassword=salzburg
      - -Dkafka.broker.url=$KAFKA_HOST:9092
      - clean
      - test
