version: '3'
services:
  maven-build:
    image: maven:3.5.3-alpine
    container_name: maven-build
    volumes:
      - ./:/opt
      - ~/.m2:/root/.m2
    entrypoint:
      -  mvn
      - -f
      - /opt/pom.xml
      - clean
      - install
