version: '3'
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper

  kafka:
    image: trivialis/kafka:1.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    entrypoint:
      - /usr/local/kafka/bin/kafka-server-start.sh
      - /usr/local/kafka/config/server.properties
      - --override
      - zookeeper.connect=zookeeper:2181
      - --override
      - listeners=PLAINTEXT://kafka:$KAFKA_PORT
      - --override
      - advertised.listeners=PLAINTEXT://$KAFKA_HOST:$KAFKA_PORT
    depends_on:
      - zookeeper

  run-test:
    image: maven:3.5.3-alpine
    container_name: log4j2-kafka-test
    volumes:
      - ./:/opt
      - ~/.m2:/root/.m2
    entrypoint:
      -  mvn
      - -f
      - /opt/pom.xml
      - -Dkafka.topic=log4j2-kafka-topic
      - -Dkafka.broker.url=$KAFKA_HOST:9092
      - clean
      - test
